// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "modelProviderGroups": string;
      "modelProviderGroupsMigrationVersion": number;
      "lastUsedModelEntryId": string;
      "systemPrompt": string;
      "lastUsedReasoningLevel": string;
      "lastReasoningExpanded": boolean;
      "panelFontScale": number;
      "customShortcuts": string;
      "shortcutOrder": string;
      "enableSemanticSearch": boolean;
      "embeddingProvider": string;
      "embeddingApiBase": string;
      "embeddingApiKey": string;
      "embeddingModel": string;
      "mineruEnabled": boolean;
      "locale": string;
    };
  }
}
